### PR TITLE
Convert to enum added.

### PR DESCRIPTION
**Pull request by isabekyan**
#78

### CODE REVIEW

**Comment by techniq** [comment]
@SimonCropp @isabekyan 

I believe I'm running into this as well... 

```
System.InvalidCastException: Invalid cast from 'System.String' to 'Namespace.MyEnum'
```

**Comment by isabekyan** [comment]
Hi.
Had no time to add enums to docs yet. Probably I will have tomorrow.

**Comment by techniq** [comment]
@isabekyan no worries, thanks for the PR/fix

@SimonCropp Any chance we could merge/release without the docs today? 😄

**Comment by techniq** [comment]
@SimonCropp Regarding, the docs, I'm guessing just adding a link in the README [here](https://github.com/SimonCropp/GraphQL.EntityFramework#supported-types-1) and maybe a link to the [graph-dotnet](https://graphql-dotnet.github.io/docs/getting-started/schema-types#enumerations) docs regarding Enums?

Also, I had to be explicit with my field type for an enum...
```c#
Field(x => x.EnumProp, type: typeof(MyEnumGraph));
```

not sure if this is common...

**Comment by SimonCropp** [comment]
@techniq 

>  Regarding, the docs, I'm guessing just adding a link in the README [here](https://github.com/SimonCropp/GraphQL.EntityFramework#supported-types-1) and maybe a link to the [graphql-dotnet](https://graphql-dotnet.github.io/docs/getting-started/schema-types#enumerations) docs regarding Enums?

yep that would suffice

> Any chance we could merge/release without the docs today?

yep done. give nuget 20min to re-index

**Comment by techniq** [comment]
Thanks Simon. I'll pull it down this evening and let you know. I'll send a
docs PR as well.

Any idea if specifying the enum type is always required (comment up above?)

**Comment by techniq** [comment]
@isabekyan @SimonCropp Thanks for the PR and quick turnaround on pushing to Nuget.  This fixed my issue.

I created a [PR](https://github.com/SimonCropp/GraphQL.EntityFramework/pull/82) to add Enum to the readme.

**Comment by isabekyan** [comment]
@techniq thanks for docs update. Still under time-pressure (

**Pull request merged**
