### PR TITLE
Multi-target to .NET Standard 2.1

### PR DESCRIPTION
**Pull request by MelbourneDeveloper**
I know how you feel about multi-targeting, but if you're keen to support .NET Standard 2.1, it's only a couple of lines of code to change. This is for an NFP and we don't know if we will be able to run with .NET 5 yet.

### CODE REVIEW

**Comment by SimonCropp** [comment]
nfp?

**Comment by MelbourneDeveloper** [comment]
Not for profit

**Comment by MelbourneDeveloper** [comment]
If it's a headache, we can upgrade to .net 5. We just haven't done that yet.

**Comment by SimonCropp** [comment]
isnt it a trivial amount of work to update your project to net5?

**Comment by MelbourneDeveloper** [comment]
Depends how well azure web apps work with it. It's hot off the press. 

https://azure.microsoft.com/en-au/updates/net-5-now-available-in-app-service/

**Comment by MelbourneDeveloper** [comment]
But this one change also your code to run on phones. 

I can think of use cases

**Comment by SimonCropp** [comment]
Let me know if there is any actual friction in you updating to net 5 and i will reconsider this

**Comment by Intecpsp** [comment]
I can agree with this. I don't think we'll be updating to 5, but instead wait for 6 since 5 isn't LTS and stay on 3.1.

**Comment by SimonCropp** [comment]
@Intecpsp ok

**Comment by mcguirepr** [comment]
I'm looking at using this in conjunction with Xamarin, so adding this in would be helpful for me as well until NET 6 is released at the end of the year and merges in Xamarin support.

**Comment by MelbourneDeveloper** [comment]
Even when it is released, there will be a tonne of old apps that won't have a straight forward upgrade path @mcguirepr

**Comment by SimonCropp** [comment]
@mcguirepr given this is a server side tech, can u explain how it can be used inside Xamarin?

**Comment by MelbourneDeveloper** [comment]
It's not necessarily a server side tech. You could use this for querying a local database. That requirement does exist.

**Comment by SimonCropp** [comment]
@MelbourneDeveloper if u r local, u would just query directly, u would not go through graphql

**Comment by MelbourneDeveloper** [comment]
That's just an assumption. 

I have built phone apps that allow users to dynamically query the local database for offline capability. 

GraphQL is prime for this

**Comment by SimonCropp** [comment]
u r going me extremely unlikely hypothetic edge cases. if someone actually has a real blocker, where they cant use (or easily move) net 5, they i am happy to have a conversation with them

**Comment by Intecpsp** [comment]
I just wanted to bump this and say that this is still needed. Right now I'm having to stay back on .Net 3.1 and 11.0.0 because this project starting targeting 5 in version 12.0.0. At this point, we won't be able to update our library until 6 is full released and in our environments.

**Comment by SimonCropp** [comment]
given ef core 6 is dropping net2.1 i dont see this as worthwile

**Pull request closed without merging**
