### PR TITLE
Added integration test for a many-to-many relationship

### PR DESCRIPTION
**Pull request by elertan**

### CODE REVIEW

**Comment by SimonCropp** [comment]
I think u need to rebase this. Have a look at the multiple commits

**Comment by SimonCropp** [comment]
U need a. Few more moving patts for an integration test. U need the models, graphs, and the method that sets up the data and runs the scenario

**Comment by elertan** [comment]
Okay @SimonCropp . I'll look into it tomorrow!

**Comment by SimonCropp** [comment]
bump

**Comment by elertan** [comment]
Hi @SimonCropp .

Sorry, but I don't have any time available to work on this, I do have a working solution though, which includes a Join instead of using select to stay on the IQueryable type. I'll push the code to my repo, in case you're interested.

I might finish up this PR some later time, I'll just close it for now.

**Pull request closed without merging**
