### PR TITLE
Removed unnecessary comma and duplicate Decimal reference

### PR DESCRIPTION
**Pull request by elertan**

### CODE REVIEW

**Comment by SimonCropp** [comment]
Sorry but i prefer to use the Oxford comma approach

**Comment by elertan** [comment]
Didn't even know that was a thing! No problem.

**Comment by SimonCropp** [comment]
i find this is the best way to explain it to people

image

**Comment by SimonCropp** [comment]
sorry i missed the duplicate decimal

**Comment by SimonCropp** [comment]
merged the duplicate decimal part. thanks

**Pull request merged**
