### PR TITLE
Adding support for non-Windows machines to run SampleWeb

### PR DESCRIPTION
**Pull request by Intecpsp**
Where it is clear the below content has not read, the issue is likely to be closed with "please read the template". Please don't take offense at this. It is simply a time management decision. When someone raises an issue, without reading the template, then often too much time is spent going back and forth to obtain information that is outlined below.

#### You should already be a Patron

To be using this project you should be a [Patron](https://opencollective.com/graphqlentityframework/order/8286). See [Licensing/Patron FAQ](https://github.com/SimonCropp/graphqlentityframework/blob/master/docs/licensing-patron-faq.md). With that in mind, it is assumed anyone raising a PR is already a Patron. As such your GitHub Id may be verified against the [OpenCollective contributors](https://opencollective.com/graphqlentityframework#contributors). This process will depend on the PR quality, your circumstances, and the impact on the larger user base.

#### Guidance

If you are uncertain if the PR will be accepted, outline the proposal in an issue to confirm it is viable.

Even if the feature is a good idea and viable, it may not be accepted since the ongoing effort in maintaining the feature may outweigh the benefit it delivers.

#### Description

Use InMemory Sqlite instead of LocalDb on non-Windows machines

#### The solution

Use InMemory Sqlite instead of LocalDb on non-Windows machines. I didn't want to create a physical database, so in memory was the initial thought. And Microsoft recommends Sqlite for in memory, so that is how I ended up here.

#### Todos

 * [ ] Related issues
 * [ ] Tests
 * [ ] Documentation

### CODE REVIEW

**Comment by SimonCropp** [comment]
i cant see your name on the open collective patron list

**Comment by Intecpsp** [comment]
I don't see why not.. 

Screenshot_20210614-182553
Screenshot_20210614-182617

**Comment by SimonCropp** [comment]
sorry, my mistake. can u change this PR to add a new sample project (that uses in mem) instead of updating the current one?

**Comment by Intecpsp** [comment]
I can, but then both projects would have to be up kept. Why not have it determine internally which technology to use so that any changes only have to happen once going forward?

**Comment by SimonCropp** [comment]
i am contemplating archiving this project. so i wont get to this. feel free to fork

**Pull request closed without merging**
