### PR TITLE
Add Enum to README

### PR DESCRIPTION
**Pull request by techniq**

### CODE REVIEW

**Comment by SimonCropp** [comment]
Sorry for the hassle. But u need to edit the .source.md then re run the test. 
Have a look at the header on the readme 
https://raw.githubusercontent.com/SimonCropp/GraphQL.EntityFramework/master/readme.md

**Comment by techniq** [comment]
No worries. I'll try to update this tonight

**Comment by techniq** [comment]
@SimonCropp done

**Comment by SimonCropp** [comment]
awesome. thanks

**Pull request merged**
