### PR TITLE
Suggestion: Add async to field names that have async parameters

### PR DESCRIPTION
**Pull request by Shane32**
I suggest you add "Async" to the end of the name of methods that have async parameters.  This matches the Microsoft convention, and the GraphQL framework convention (e.g. FieldAsync vs Field).  This is a breaking change.

* Patron under name of Zbox.

### CODE REVIEW

**Comment by Shane32** [comment]
Apparently, both suggestions cannot be auto merged, as a few of the lines of code changed in both pull requests.  If you want to accept both pull requests, let me know and I'll merge the pull requests before you pull in the changes.

**Comment by SimonCropp** [comment]
the recommendation from MS is for methods that "are async" to have the suffix "Async". none of the methods highlighted fit that criteria. I know GraphQL  takes this approach, but i think it is an invalid convention

**Comment by Shane32** [comment]
That’s true but this isn’t exactly typical code. It’s metadata being defined in a singleton.  The code does nothing except define metadata.  You could write the function to be an async function. It still would do nothing. And as the only portion of the code that “does something” (albeit in the future) is async (the resolve function), personally, I would expect the function to end in Async, even though technically it’s not an async function. Just my thoughts.

**Comment by SimonCropp** [comment]
Sorry, but we will have to agree to disagree on this one. Sorry for the effort you put into this one

**Pull request closed without merging**
